### ISSUE TITLE
Error listing challenges

### ISSUE THREAD

**Issue by noraj** [koromodako/mkctf#2]
Error listing challenges when no one exists (0 challenge):

This case need to be handle.

```
[?] > What do you want to do ?
4

Challenges:
	bugbounty:
Traceback (most recent call last):
  File "py_chall_factory.py", line 112, in <module>
    menu(dispatcher, options_parser)
  File "py_chall_factory.py", line 94, in menu
    dispatcher_call(dispatcher, options_parser, OPTIONS[choice-1][0])
  File "py_chall_factory.py", line 54, in dispatcher_call
    dispatcher.call(opt)
  File "/home/noraj/py_chall_factory/core/dispatcher.py", line 29, in call
    self.dispatch.get(key, not_implemented)(kwargs)
  File "/home/noraj/py_chall_factory/core/functions.py", line 130, in list_challenges
    for chall in os.listdir(os.path.join(root, category)):
FileNotFoundError: [Errno 2] No such file or directory: 'challenges/bugbounty'
```

**Comment by koromodako** [comment]
That's right there is a little glitch here :+1: 
I'll correct that when I have some time.

Thank you very much!
